### ISSUE TITLE
Cannot run the examples

### ISSUE THREAD

**Issue by Hephaest** [isaksamsten/wildboar#12]
**Describe the bug**
I want to run the **shapelet_forest_example.py** but it ends at reporting the following traceback:
```
Traceback (most recent call last):
  File "D:/MachineLearningDeveloper/wildboar/examples/shapelet_forest_example.py", line 5, in <module>
    from wildboar.ensemble import ExtraShapeletTreesClassifier, ShapeletForestClassifier
  File "D:\MachineLearningDeveloper\wildboar\wildboar\ensemble\__init__.py", line 18, in <module>
    from ._ensemble import ShapeletForestClassifier
  File "D:\MachineLearningDeveloper\wildboar\wildboar\ensemble\_ensemble.py", line 32, in <module>
    from ..tree import ExtraShapeletTreeClassifier
  File "D:\MachineLearningDeveloper\wildboar\wildboar\tree\__init__.py", line 18, in <module>
    from ._tree import ShapeletTreeClassifier
  File "D:\MachineLearningDeveloper\wildboar\wildboar\tree\_tree.py", line 24, in <module>
    from ._tree_builder import ClassificationShapeletTreeBuilder
ModuleNotFoundError: No module named 'wildboar.tree._tree_builder'
```

**To Reproduce**
run the shapelet_forest_example.py

**Expected behavior**
Expect to print out results in the console.

**Setup (please complete the following information):**
 - OS: Windows 10 64-bit
 - Python version: 3.8.6
 - NumPy version: 1.18.5
 - Cython version: 0.29.21

**Additional context**
None

**Comment by Hephaest** [comment]
@isaksamsten Please help me, thanks!

**Comment by isaksamsten** [comment]
Thanks for your report!

What version of wildboar are you running?

How did you install? Pip? Or did you compile it?

**Comment by Hephaest** [comment]
Dear Isak,

I fixed the problem after following your [installation guide](https://isaksamsten.github.io/wildboar/master/install.html). 

I guess the issue happened for the lack of a C ++ compiler. Because there is `_tree_builder.py` and the only source code is '_tree_builder.c'. After I installed the C ++ compiler by installing **Visual Studio Build Tools 2019**, I can successfully compile and generate the stuff like `_tree_builder.cp38-win_amd64.pyd`.

Yet that is the whole story. I think this may be a little trap for some newbies, and you can also provide the link I mentioned above in the `README.md`.

❤️ from Hephaest

**Comment by isaksamsten** [comment]
Great! Glad it works!

I'll update the readme with links to the installation guide.
