### ISSUE TITLE
ShapeletForestClassifier error with multivariate time-series of different lengths

### ISSUE THREAD

**Issue by LorenzoBonasera** [isaksamsten/wildboar#29]
Dear Isak,

when I try to fit the ShapeletForestClassifier (scaled_dtw) on a nested dataframe containing multivariate time-series of different lengths, I get the following error:

"ValueError: setting an array element with a sequence."

If I try to fit on a Multiindex Dataframe, I get the following error instead:

"ValueError: Number of labels=712 does not match number of samples=509628"

It seems that it cannot handle multivariate time-series of different lengths, but yet the scaled dtw metric should work on such items.
I kindly ask for your help. 

Thanks in advance.

**Comment by isaksamsten** [comment]
ShapeletForest does not support variable length time series. While straight forward to implement, it would complicate the code significantly so I'm hesitant to support it unless I can figure out a good alternative solution. 

Perhaps you can truncate the time series to a common length or Downsample the to long sequence
