### ISSUE TITLE
Extraction of Shapelets and return as a list

### ISSUE THREAD

**Issue by LorenzoBonasera** [isaksamsten/wildboar#30]
Dear Isak Samsten,

is it possible to retrieve/obtain all the shapelets extracted by ShapeletForestClassifier?
Which part of the code has to be modified? I could do it alone.

Thanks in advance,

LB

**Comment by isaksamsten** [comment]
Hi,

You can find the shapelets in the `tree` attribute.  `forest.estimators_[0].tree.features` give a list of the shapelets of the first tree in the ensemble. Check the _tree.py file for details. The tree has the same structure as a tree in sklearn so examples for extracting features of such trees can be adapted.

**Comment by LorenzoBonasera** [comment]
Thanks, I've managed to retrieve shapelets.
I have another question: the `forest.estimators_[0].tree.feateures` list contains several values.

For example:
features[0] = (1, array([....]))
features[1] = None
features[2] = (1, array([....]))
features[3] = None
features[4] = None
etc...

It seems that some elements are None, while other are in the form (number, array). I think that maybe the array is the shapelet and the number is the target class.

Why are some elements None? Why does the number of elements in the list differ from a tree to another?

Thank you again!

**Comment by isaksamsten** [comment]
If the value is `None` the node index refers to a leaf node. The first element of the tuple refers to the dimension of the input data and the second is the shapelet.

**Comment by isaksamsten** [comment]
The number of features depend on the depth of the tree. Not all trees are equally deep.

**Comment by isaksamsten** [comment]
Here is an example where all branches are visited: https://github.com/isaksamsten/wildboar/blob/9348d46422bf9665b5aa67f17aa397191764e85b/src/wildboar/explain/counterfactual/_sf.py#L71

**Comment by madarax64** [comment]
Hi @isaksamsten ,
I stumbled upon this thread while looking for similar functionality...in my own usage, I found that I was able to access the shapelets as (assuming the classifier object is called `clf` and assuming the first tree at index 0):

`clf.estimators_[0].estimator.tree_.shapelet` 

Rather than the way you described above. Is this way correct or am I missing something?
Thanks!

**Comment by isaksamsten** [comment]
Hi!

You are not missing anything. For version 1.1, the `shapelet` attribute is renamed `features. `

**Comment by madarax64** [comment]
Hello!
Ah, got it. v1.1 is seemingly not on pip yet, so I'll just make a note to update my code when it comes out. Thanks for the clarification and the amazing work!

**Comment by isaksamsten** [comment]
Not yet. The update is rather massive and I want to make sure that there aren’t too many regressions. (I will try to write a migration guide too 😱)

**Comment by madarax64** [comment]
Haha, that's ok. Thank you once again for the amazing work!
