### ISSUE TITLE
Impurity at forest nodes is always -1 in Multivariate Shapelet Forest Classifier

### ISSUE THREAD

**Issue by LorenzoBonasera** [isaksamsten/wildboar#31]
Dear Isak Samsten,

while I was checking the internal attributes of ShapeletForestClassifier after the `fit` method was called, I noticed that the `Impurity` attribute for each node of one hundred trees was alywas -1. 

I think it is an error, maybe due to the bad structure of my data. Do you have any suggestions?

Thanks in advance!

**Comment by isaksamsten** [comment]
Hi!

It’s not yet implemented. 

Please open an issue and I’ll try to prioritise it.

**Comment by isaksamsten** [comment]
Apparently I don't remember what I've implemented. But in the latest development versions impurity should be correctly set for non-leaf nodes. For leaf-nodes the impurity is -1.
