### ISSUE TITLE
_joblib_parallel_args removed from scikit-learn

### ISSUE THREAD

**Issue by david-waterworth** [isaksamsten/wildboar#34]
**Describe the bug**
You're importing `_joblib_parallel_args` from `sklearn.fixes` however it's been removed

**To Reproduce**

$ pip install "scikit-learn>=0.21.3"
Requirement already satisfied: scikit-learn>=0.21.3 in ./.venv/lib/python3.8/site-packages (from wildboar) (1.1.1)

from sklearn.utils.fixes import _joblib_parallel_args
ImportError: cannot import name '_joblib_parallel_args' from 'sklearn.utils.fixes'

$ pip install "scikit-learn<=1.1.0"
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.1.1
    Uninstalling scikit-learn-1.1.1:
      Successfully uninstalled scikit-learn-1.1.1
Successfully installed scikit-learn-1.0.2

from sklearn.utils.fixes import _joblib_parallel_args

**Expected behavior**
Compatible with latest version(s) of scikit-learn (>1.0.2)

**Setup (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.8
 - Wildboar version: 1.0.12

**Comment by david-waterworth** [comment]
Actually I see you've fixed that in https://github.com/isaksamsten/wildboar/commit/669a01f124e01feb9a54bd69f565aeeabd21f41d

I'll install from source

**Comment by isaksamsten** [comment]
Thanks for reporting the second issue. I’ll see if I can figure out what changes I’ve made to introduce the error.
